import { type Game } from "./types"

// Sample data - replace with your actual collection
export const GAMES: Game[] = [
  {
    id: "1",
    title: "Gloomhaven: Jaws of the Lion",
    year: 2020,
    language: "EN",
    players: "1-4",
    playtime: "30-120 min",
    condition: "Factory Sealed",
    price: 350,
    currency: "RON",
    tags: ["Campaign", "Dungeon Crawler", "Fantasy"],
    isKickstarter: false,
    bggLink: "https://boardgamegeek.com/boardgame/291457/gloomhaven-jaws-of-the-lion",
    image: "/gloomhaven-jaws-of-the-lion-board-game-box.jpg",
    highlights: ["Never opened", "Shrink wrap intact", "Perfect condition"],
  },
  {
    id: "2",
    title: "Wingspan European Expansion",
    year: 2019,
    language: "EN",
    players: "1-5",
    playtime: "40-70 min",
    condition: "Opened but Unplayed",
    price: 180,
    currency: "RON",
    tags: ["Engine Building", "Animals", "Card Game"],
    isKickstarter: true,
    bggLink: "https://boardgamegeek.com/boardgame/253956/wingspan-european-expansion",
    kickstarterLink: "https://www.kickstarter.com/projects/stonemaiergames/wingspan",
    image: "/wingspan-european-expansion-board-game.jpg",
    highlights: ["Box opened only to check contents", "All components mint", "Kickstarter exclusive"],
  },
  {
    id: "3",
    title: "Spirit Island",
    year: 2017,
    language: "EN",
    players: "1-4",
    playtime: "90-120 min",
    condition: "Like New",
    price: 420,
    currency: "RON",
    tags: ["Cooperative", "Strategy", "Fantasy"],
    isKickstarter: true,
    bggLink: "https://boardgamegeek.com/boardgame/162886/spirit-island",
    kickstarterLink: "https://www.kickstarter.com/projects/2010555768/spirit-island",
    image: "/spirit-island-board-game-box.jpg",
    highlights: ["Played twice", "All components present", "Includes promo spirits"],
  },
  {
    id: "4",
    title: "Brass: Birmingham",
    year: 2018,
    language: "EN",
    players: "2-4",
    playtime: "60-120 min",
    condition: "Factory Sealed",
    price: 480,
    currency: "RON",
    tags: ["Economic", "Industry", "Network Building"],
    isKickstarter: true,
    bggLink: "https://boardgamegeek.com/boardgame/224517/brass-birmingham",
    kickstarterLink: "https://www.kickstarter.com/projects/roxley/brass-an-industrial-revolution",
    image: "/brass-birmingham-deluxe-board-game.jpg",
    highlights: ["Deluxe edition", "Never opened", "Metal coins included"],
  },
  {
    id: "5",
    title: "Terraforming Mars",
    year: 2016,
    language: "EN",
    players: "1-5",
    playtime: "120 min",
    condition: "Very Good",
    price: 280,
    currency: "RON",
    tags: ["Science Fiction", "Economic", "Card Game"],
    isKickstarter: false,
    bggLink: "https://boardgamegeek.com/boardgame/167791/terraforming-mars",
    image: "/terraforming-mars-board-game.jpg",
    highlights: ["Cards sleeved", "Player boards included", "Light wear on box"],
  },
  {
    id: "6",
    title: "Scythe",
    year: 2016,
    language: "EN",
    players: "1-5",
    playtime: "90-115 min",
    condition: "Factory Sealed",
    price: 520,
    currency: "RON",
    tags: ["Area Control", "Economic", "Sci-Fi"],
    isKickstarter: true,
    bggLink: "https://boardgamegeek.com/boardgame/169786/scythe",
    kickstarterLink: "https://www.kickstarter.com/projects/jameystegmaier/scythe",
    image: "/scythe-board-game-box-cover.jpg",
    highlights: ["Legendary Box", "All expansions", "Never opened"],
  },
]

